export default Object.freeze({
  HOME_SCREEN: 'HOME_SCREEN',
  FETCH_DATA_SCREEN: 'FETCH_DATA_SCREEN',
  FORM_SCREEN: 'FORM_SCREEN',
  BLUETOOTH_SCREEN: 'BLUETOOTH_SCREEEN',
  BLUETOOTH_LISTENER_SCREEN: 'BLUETOOTH_LISTENER_SCREEN',
  BLUETOOTH_LISTENER_PLX_SCREEN: 'BLUETOOTH_LISTENER_PLX_SCREEN',
});
